### PR TITLE
Use asyncio.Protocol/asyncio.DatagramTransport directly

### PR DESCRIPTION
**Pull request by bdraco**
- Fixes log spam when the device is online

### CODE REVIEW

**Comment by bdraco** [comment]
@sbidy This should take care of the chatty logs when the device is offline

```
2022-02-05 15:39:02 ERROR (MainThread) [homeassistant.components.wiz] Error fetching WiZ Dimmable White 2034FD data: Failed to update device at 192.168.214.86: The request to the bulb timed out
2022-02-05 15:39:46 INFO (MainThread) [homeassistant.components.wiz] Fetching WiZ Socket 9C1599 data recovered
```

**Comment by bdraco** [comment]
Looks like github is being flakey as I pushed a few more commits but they aren't showing

**Comment by bdraco** [comment]
Force pushing it got github to catch up

**Comment by sbidy** [comment]
https://github.com/all-contributors please add @bdraco code

**Comment by sbidy** [comment]
[bdraco](https://github.com/bdraco)

**Comment by sbidy** [comment]
@all-contributors please add @bdraco code

**Comment by bdraco** [comment]
Thanks @sbidy 👍

**Pull request merged**
