### PR TITLE
Improve performance

### LINKED ISSUE #105: Implement backoff when bulb is offline
We try really hard to reach the bulb when it is offline. 

Screen Shot 2022-02-07 at 16 17 22

Retry should use a progressive backoff as its using a bit of cpu time if there are many offline bulbs

### LINKED ISSUE #106: Fix race condition during unload of integration when bulb is offline
This doesn't cause a user visible user but does generate log spam

```
2022-02-07 22:21:46 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 353, in _async_send_register
    await self.sendUDPMessage(message)
  File "/usr/local/lib/python3.9/site-packages/pywizlight/bulb.py", line 568, in sendUDPMessage
    self.transport.sendto(data, (self.ip, self.port))
AttributeError: 'NoneType' object has no attribute 'sendto'
```

If the integration is unloaded right in the middle of a send retry when a device is offline, the transport can be deleted out from under it.  We need to guard here to make sure `self.transport` is not None

### LINKED ISSUE #107: Fix memory leak in discovery
There is a risk of leaking since `self.loop.call_later(1, self.broadcast_registration)` keeps calling and if `self.transport` is never cleared it will run as long as the object exists

### PR DESCRIPTION
**Pull request by bdraco**
- Improves performance when bulb is offline

- Fixes python 3.8 typing compat

- Fixes race condition during shutdown

- Fixes memory leak in discovery

- Fixes slow tests

- Adds test runs to the CI

- No longer respond to `syncPilot` messages since the
  bulb keeps sending them anyways and all it does
  is generate additional network congestion

fixes #107,  fixes #106, fixes #105

### CODE REVIEW

**Comment by sbidy** [comment]
We should be aware of the #109. The IP can also be a DNS name. Especially in the HASS config flow if I enter a DNS name of a bulb manually.

https://github.com/sbidy/pywizlight/blob/cb6c00109fbbc18c7b0bf99466a0909fcaec1529/pywizlight/bulb.py#L301

I would suggest adding a `self.ip = socket.gethostbyname(ip)` to unify to IPs only.

**Comment by bdraco** [comment]
> @bdraco We should be aware of the #109. The IP can also be a DNS name. Especially in the HASS config flow if I enter a DNS name of a bulb manually.

Usually we don't want to accept dns names since if dns is having issues the device can't be setup.  As soon as discovery sees the bulb it will update it to an ip address via 

https://github.com/home-assistant/core/blob/dev/homeassistant/components/wiz/config_flow.py#L61

This takes care of the case where the bulb's dhcp reservation changes.



> ```python
> def _resolve_dnsname(self, dns_or_ip: str):
>         """Returns a IP in case of a DNS was given."""
>         try:
>             return socket.gethostbyname(dns_or_ip)
>         except socket.gaierror:
>             raise WizLightConnectionError("DNS name can not be resloved.")
> ```

If we do want to do allow a hostname, we need to use `loop.getaddrinfo()` since it is async safe.

**Comment by bdraco** [comment]
Screen Shot 2022-02-08 at 13 07 18


This is looking really efficient now.  The debug logging is taking far more time than the actual protocol ops

**Comment by bdraco** [comment]
Screen Shot 2022-02-08 at 13 11 01


The offline case looks a lot better as well with `sendto` being the bulk of the time.  We can't improve that though since its low level

**Pull request merged**
