### PR TITLE
Fix KeyError when sceneId is missing

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by bdraco** [comment]
I just had some more devices show up so I'm going to see if I can add motion sensor support

**Comment by sbidy** [comment]
I'm not sure, but I think the motion sensor is a BLE device and doesn't communicate via Wi-Fi. Do you have one?

**Comment by bdraco** [comment]
Just got one. Unboxing it now

**Comment by bdraco** [comment]
Looks like its detectable on the light with `src` `pir`
```
2022-02-09 14:51:58 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.209.205', 49155): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb5087933b","rssi":-60,"src":"pir","state":false,"sceneId":0,"temp":2762,"dimming":100}}'
2022-02-09 14:51:58 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-70,"src":"pir","state":false,"sceneId":0}}'
```

**Comment by bdraco** [comment]
```
2022-02-09 14:51:58 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-70,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:08 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:09 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-70,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:28 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-67,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:29 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:52:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:53:08 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:53:09 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:53:28 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-67,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:53:29 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-68,"src":"pir","state":false,"sceneId":0}}'
2022-02-09 14:53:40 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.214.216', 64299): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb50d46a1c","rssi":-48,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:40 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.68', 52195): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"6c2990f7743e","rssi":-45,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:40 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.211.79', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb50818e7c","rssi":-57,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:40 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.210.189', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c0e96","rssi":-71,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:40 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-69,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:48 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.68', 52195): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"6c2990f7743e","rssi":-44,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:48 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-71,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:48 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.211.79', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb50818e7c","rssi":-59,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:48 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.210.189', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c0e96","rssi":-72,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.173', 49154): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c1599","rssi":-71,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.212.68', 52195): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"6c2990f7743e","rssi":-44,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.211.79', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb50818e7c","rssi":-57,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
2022-02-09 14:53:49 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.210.189', 49156): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb509c0e96","rssi":-72,"src":"pir","state":true,"sceneId":0}}'
2022-02-09 14:53:51 DEBUG (MainThread) [pywizlight.push_manager] ('192.168.214.216', 64299): PUSH << b'{"method":"syncPilot","env":"pro","params":{"mac":"a8bb50d46a1c","rssi":-48,"src":"pir","state":true,"sceneId":27,"speed":100,"dimming":100}}'
```

**Comment by sbidy** [comment]
Does the motion sensor provide a UDP interface?

**Comment by bdraco** [comment]
The motion sensor is BLE only so we have to get the state from the light

**Comment by sbidy** [comment]
Ah, ok. But the state change at the bulb property should be fast enough to avoid a latency gap.

**Pull request merged**
