### PR TITLE
Add support for getPower api

### LINKED ISSUE #130: Energy data
Investigate if its possible to get energy data from the device to show in Home Assistant

### PR DESCRIPTION
**Pull request by bdraco**
Closes #130

### CODE REVIEW

**Comment by bdraco** [comment]
It looks like its actually being pushed as well

**Comment by bdraco** [comment]
`pc`

**Comment by bdraco** [comment]
Thanks 👍

**Comment by sbidy** [comment]
> Thanks 👍

Thank you 😄

**Pull request merged**
