### PR TITLE
Fix compat with 1.8.0 firmware

### PR DESCRIPTION
**Pull request by bdraco**

### CODE REVIEW

**Comment by bdraco** [comment]
I'll fix the conflict

**Comment by sbidy** [comment]
Ah, shit. I missed the draft.

**Comment by bdraco** [comment]
@sbidy should be good now

**Comment by bdraco** [comment]
Thanks @sbidy 

Would you mind pushing a new release?

**Comment by sbidy** [comment]
Done

**Comment by bdraco** [comment]
Thanks!

**Pull request merged**
